'USA, State 1':
  - 'State Building 1'
  - 'State Building 2'
'USA, State 2':
  - 'State Building 3'
  - 'State Building 4'
'Wayne State':
  - 'Mike Ilitch School of Business'
  - 'College of Education'
  - 'College of Engineering'
  - 'College of Fine, Performing and Communication Arts'
  - 'Graduate School'
  - 'Irvin D. Reid Honors College'
  - 'Law School'
  - 'College of Liberal Arts and Sciences'
  - 'School of Information Sciences'
  - 'School of Medicine'
  - 'College of Nursing'
  - 'Eugene Applebaum College of Pharmacy and Health Sciences'
  - 'School of Social Work'
  - 'Anthony Wayne Drive Apartments'
  - 'University Tower Apartments'
  - 'Atchison Hall'
  - 'Towers Suites'
'Wayne State, On Campus':
  - 'Mike Ilitch School of Business'
  - 'College of Education'
  - 'College of Engineering'
  - 'College of Fine, Performing and Communication Arts'
  - 'Graduate School'
  - 'Irvin D. Reid Honors College'
  - 'Law School'
  - 'College of Liberal Arts and Sciences'
  - 'School of Information Sciences'
  - 'School of Medicine'
  - 'College of Nursing'
  - 'Eugene Applebaum College of Pharmacy and Health Sciences'
  - 'School of Social Work'
  - 'Anthony Wayne Drive Apartments'
  - 'University Tower Apartments'
  - 'Atchison Hall'
  - 'Towers Suites'
'Wayne State, Off Campus':
  - 'Mike Ilitch School of Business'
  - 'College of Education'
  - 'College of Engineering'
  - 'College of Fine, Performing and Communication Arts'
  - 'Graduate School'
  - 'Irvin D. Reid Honors College'
  - 'Law School'
  - 'College of Liberal Arts and Sciences'
  - 'School of Information Sciences'
  - 'School of Medicine'
  - 'College of Nursing'
  - 'Eugene Applebaum College of Pharmacy and Health Sciences'
  - 'School of Social Work'
  - 'Anthony Wayne Drive Apartments'
  - 'University Tower Apartments'
  - 'Atchison Hall'
  - 'Towers Suites'
'Wayne State, On Campus, College of Nursing':
  - 'Mike Ilitch School of Business'
  - 'College of Education'
  - 'College of Engineering'
  - 'College of Fine, Performing and Communication Arts'
  - 'Graduate School'
  - 'Irvin D. Reid Honors College'
  - 'Law School'
  - 'College of Liberal Arts and Sciences'
  - 'School of Information Sciences'
  - 'School of Medicine'
  - 'College of Nursing'
  - 'Eugene Applebaum College of Pharmacy and Health Sciences'
  - 'School of Social Work'
  - 'Anthony Wayne Drive Apartments'
  - 'University Tower Apartments'
  - 'Atchison Hall'
  - 'Towers Suites'
'Wayne State, On Campus, Medical School':
  - 'Mike Ilitch School of Business'
  - 'College of Education'
  - 'College of Engineering'
  - 'College of Fine, Performing and Communication Arts'
  - 'Graduate School'
  - 'Irvin D. Reid Honors College'
  - 'Law School'
  - 'College of Liberal Arts and Sciences'
  - 'School of Information Sciences'
  - 'School of Medicine'
  - 'College of Nursing'
  - 'Eugene Applebaum College of Pharmacy and Health Sciences'
  - 'School of Social Work'
  - 'Anthony Wayne Drive Apartments'
  - 'University Tower Apartments'
  - 'Atchison Hall'
  - 'Towers Suites'
'Wayne State, On Campus, Applebaum':
  - 'Mike Ilitch School of Business'
  - 'College of Education'
  - 'College of Engineering'
  - 'College of Fine, Performing and Communication Arts'
  - 'Graduate School'
  - 'Irvin D. Reid Honors College'
  - 'Law School'
  - 'College of Liberal Arts and Sciences'
  - 'School of Information Sciences'
  - 'School of Medicine'
  - 'College of Nursing'
  - 'Eugene Applebaum College of Pharmacy and Health Sciences'
  - 'School of Social Work'
  - 'Anthony Wayne Drive Apartments'
  - 'University Tower Apartments'
  - 'Atchison Hall'
  - 'Towers Suites'